import { test, expect } from "@playwright/test";

test("new content widgets publish and containers move with children to any region", async ({page}) => {
  await page.goto("/");
  await page.getByRole("button", {name:"Page builder",exact:true}).click();
  await page.getByRole("button", {name:"Edit in page builder",exact:true}).first().click();
  await page.getByRole("button", {name:"Add Container to Header",exact:true}).click();
  await page.getByRole("button", {name:"Add Text to Header",exact:true}).click();
  const inspector = page.getByRole("complementary", {name:"Widget editor"});
  await inspector.getByLabel("Title", {exact:true}).fill("Text in any region");
  await inspector.getByLabel("Text", {exact:true}).fill("A separate text widget");
  const container = page.locator(".widget-container");
  await expect(container.locator(".widget-text")).toContainText("Text in any region");
  await container.getByRole("button", {name:"Edit Container",exact:true}).click();
  await inspector.getByLabel("Placement", {exact:true}).selectOption("Footer");
  await expect(page.locator(".store-region-footer > .widget-container .widget-text")).toContainText("A separate text widget");
  await page.getByRole("button", {name:"Add Image to Footer",exact:true}).click();
  await inspector.getByLabel("Image alternative text", {exact:true}).fill("Handmade collection");
  await inspector.getByLabel("Image URL (HTTPS)", {exact:true}).fill("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=300");
  await expect(page.locator(".widget-container").getByRole("img", {name:"Handmade collection"})).toBeVisible();
  await page.getByRole("button", {name:"Add Html to Main",exact:true}).click();
  await inspector.getByLabel("HTML code").fill('<style>h2{color:purple}</style><article><h2>Custom markup</h2><p>Custom HTML works</p></article>');
  const frame = page.frameLocator('iframe[title="Custom HTML widget"]');
  await expect(frame.getByRole("heading", {name:"Custom markup"})).toBeVisible();
  await expect(page.locator('iframe[title="Custom HTML widget"]')).toHaveAttribute("sandbox", "");
  await inspector.getByLabel("HTML code").fill('<script>window.top.location="https://example.com"</script>');
  await expect(page.locator(".html-widget-error")).toBeVisible();
  await page.getByRole("button", {name:"Publish",exact:true}).click();
  await expect(page.getByRole("alert").filter({hasText:"Scripts"})).toBeVisible();
  await inspector.getByLabel("HTML code").fill('<h2>Published custom markup</h2>');
  await page.getByRole("button", {name:"Publish",exact:true}).click();
  await page.getByRole("button", {name:"Share published demo",exact:true}).click();
  const shared = await page.getByRole("link", {name:"Open shared storefront"}).getAttribute("href");
  expect(shared).toContain("/shared-storefront#");
  await page.goto(shared!);
  await expect(page.locator(".widget-container .widget-text")).toContainText("Text in any region");
  await expect(page.frameLocator('iframe[title="Custom HTML widget"]').getByRole("heading", {name:"Published custom markup"})).toBeVisible();
  await page.goto("/s/sunday-supply");
  await expect(page.locator(".widget-container .widget-text")).toContainText("Text in any region");
  await expect(page.getByRole("img", {name:"Handmade collection"})).toBeVisible();
  await expect(page.frameLocator('iframe[title="Custom HTML widget"]').getByRole("heading", {name:"Published custom markup"})).toBeVisible();
});
